=====Exception Log DateTime:5/29/2020 2:37:17 PM=======
https://localhost:44376/Login/Validate

NameSpace : ProAcc.Controllers
ClassName : LoginController
MethodName : Validate
MethodArguments :  , UserModel , userString , returnUrl
SOURCE    : .Net SqlClient Data Provider
Type      : System.Data.SqlClient.SqlException
MESSAGE   : A transport-level error has occurred when receiving results from the server. (provider: Session Provider, error: 19 - Physical connection is not usable)
TARGETSITE: Void OnError(System.Data.SqlClient.SqlException, Boolean, System.Action`1[System.Action])
STACKTRACE:    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at ProAcc.BL.DBHelper.ExecuteDataSet() in D:\Office\Projects\ProACC\ProAccNew\ProAcc\BL\DBHelper.cs:line 330
   at ProAcc.BL.Base.UserValidation(LogedUser user) in D:\Office\Projects\ProACC\ProAccNew\ProAcc\BL\Base.cs:line 26
   at ProAcc.Controllers.LoginController.Validate(UserModel user, String returnUrl) in D:\Office\Projects\ProACC\ProAccNew\ProAcc\Controllers\LoginController.cs:line 43

=====Exception Log End=======


=====Exception Log DateTime:5/29/2020 2:37:34 PM=======
https://localhost:44376/Login/Validate

NameSpace : ProAcc.Controllers
ClassName : LoginController
MethodName : Validate
MethodArguments :  , UserModel , userString , returnUrl
SOURCE    : .Net SqlClient Data Provider
Type      : System.Data.SqlClient.SqlException
MESSAGE   : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The wait operation timed out.)
TARGETSITE: Boolean TryGetConnection(System.Data.Common.DbConnection, UInt32, Boolean, Boolean, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal ByRef)
STACKTRACE:    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at ProAcc.BL.DBHelper.ExecuteDataSet() in D:\Office\Projects\ProACC\ProAccNew\ProAcc\BL\DBHelper.cs:line 330
   at ProAcc.BL.Base.UserValidation(LogedUser user) in D:\Office\Projects\ProACC\ProAccNew\ProAcc\BL\Base.cs:line 26
   at ProAcc.Controllers.LoginController.Validate(UserModel user, String returnUrl) in D:\Office\Projects\ProACC\ProAccNew\ProAcc\Controllers\LoginController.cs:line 43
InnerException: System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out

=====Exception Log End=======


============ProAcc.BL.Model.ProjectMonitorModel At 5/29/2020 5:55:48 PM============

============ProAcc.BL.Model.ProjectMonitorModel At 5/29/2020 5:57:06 PM============

============ProAcc.BL.Model.ProjectMonitorModel At 5/29/2020 5:59:09 PM============

============5/31/2020 12:00:00 AM At 5/29/2020 6:03:35 PM============

============5/29/2020 12:00:00 AM At 5/29/2020 6:31:40 PM============

============5/29/2020 12:00:00 AM At 5/29/2020 6:36:23 PM============

============5/29/2020 12:00:00 AM At 5/29/2020 6:36:51 PM============

============5/29/2020 12:00:00 AM At 5/29/2020 7:52:22 PM============

============5/21/2020 12:00:00 AM At 5/29/2020 8:43:26 PM============

============5/29/2020 12:00:00 AM At 5/29/2020 8:47:29 PM============

============5/29/2020 12:00:00 AM At 5/29/2020 8:47:59 PM============

